### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by brian-norman** [Cobresun/PantsOrShorts-iOS#1]
Someone said they'd publish us if we were a widget 😂

**Comment by SunnyNagam** [comment]
What do mean publish us 😂

**Comment by brian-norman** [comment]
Put us on iOS App Store 😵

**Comment by SunnyNagam** [comment]
Lol I thought we did that ourselves like the android app store?

**Comment by SunnyNagam** [comment]
Also I didn't know iPhones had widgets

**Comment by brian-norman** [comment]
Sunny if you wanna drop $100 a year on the App Store I'm down to do it ourselves HAHA

**Comment by SunnyNagam** [comment]
LMAO I forgot about that part

**Comment by atulb98** [comment]
For reference: https://www.raywenderlich.com/697-today-extension-tutorial-getting-started
